cmake \
-DDEAL_II_WITH_LAPACK=ON \
-DDEAL_II_WITH_TRILINOS=ON \
-DTRILINOS_DIR=/InstalledPackages/trilinos \
-DDEAL_II_WITH_METIS=OFF \
-DDEAL_II_WITH_ZLIB=ON \
-DDEAL_II_WITH_MPI=ON \
-DDEAL_II_WITH_THREADS=ON \
-DDEAL_II_WITH_64BIT_INDICES=OFF \
-DDEAL_II_WITH_P4EST=ON \
-DDEAL_II_WITH_ARPACK=OFF \
-DDEAL_II_WITH_PETSC=OFF \
-DDEAL_II_WITH_UMFPACK=ON \
-DP4EST_DIR=/InstalledPackages/deal.II/p4est \
-DDEAL_II_CONSTEXPR_BUG=FALSE \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_PREFIX_PATH="/usr/local" \
-DCMAKE_C_COMPILER="/usr/local/openmpi/bin/mpicc"  \
-DCMAKE_CXX_COMPILER="/usr/local/openmpi/bin/mpicxx" \
-DDEAL_II_ALLOW_PLATFORM_INTROSPECTION=NO \
-DCMAKE_OSX_ARCHITECTURES=x86_64 \
-DDEAL_II_COMPONENT_DOCUMENTATION=ON \
-DDEAL_II_COMPONENT_EXAMPLES=ON \
-DCMAKE_INSTALL_PREFIX=../install \
../deal.II


cmake -DCMAKE_PREFIX_PATH="/usr/local" -DCMAKE_C_COMPILER="/usr/local/bin/mpicc"  -DCMAKE_CXX_COMPILER="/usr/local/bin/mpicxx" .\


